export const LOAD_POSTS_SUCCESS = 'LOAD_POSTS_SUCCESS'
export const LOAD_POST_SUCCESS = 'LOAD_POST_SUCCESS'
export const ADD_POST_SUCCESS = 'ADD_POST_SUCCESS'
export const DELETE_POST_SUCCESS = 'DELETE_POST_SUCCESS'
export const CHANGE_SORTING_SUCCESS = 'CHANGE_SORTING_SUCCESS'
export const VOTE_POST_SUCCESS = 'VOTE_POST_SUCCESS'

export const LOAD_COMMENTS_SUCCESS = 'LOAD_COMMENTS_SUCCESS'
export const ADD_COMMENT_SUCCESS = 'ADD_COMMENT_SUCCESS'
export const DELETE_COMMENT_SUCCESS = 'DELETE_COMMENT_SUCCESS'
export const VOTE_COMMENT_SUCCESS = 'VOTE_COMMENT_SUCCESS'

export const LOAD_CATEGORIES_SUCCESS = 'LOAD_CATEGORIES_SUCCESS'